completed css-layout-classes
marissalortega/m1-0122-code-solutions pull request #17
Opened 2022-02-08 05:13 UTC by marissalortega

![_Users_marissa ortega_repos_m1-0122-code-solutions_css-layout-classes_index html](https://user-images.githubusercontent.com/90414477/152922432-60d7849e-b1bc-4102-ae1e-e725d97cd779.png)

2022-02-08 05:15 UTC, Zhiwutian requested changes
Looking good, a few small updates!

2022-02-08 05:15 UTC, Zhiwutian commented on css-layout-classes/index.html
> +        <div class="half">
you want 2/3 for the text and 1/3 for the image

2022-02-08 05:15 UTC, Zhiwutian commented on css-layout-classes/index.html
> +        <div class="half">
same as above

2022-02-08 05:15 UTC, Zhiwutian commented on css-layout-classes/styles.css
> +  width: 100%;
remove all of the widths set here, you don't want to set both width and flex basis

2022-02-08 05:34 UTC, marissalortega commented
<img width="891" alt="Screen Shot 2022-02-07 at 9 32 05 PM" src="https://user-images.githubusercontent.com/90414477/152924612-e4d3ba1e-24b6-4a24-8180-d069c50c359d.png">

2022-02-09 03:21 UTC, thebearingedge approved these changes

2022-02-09 04:22 UTC, merged